### ISSUE TITLE
"Unnormalized Log Probability of Visible Units" in GaussianRBM seems to be incorrect

### ISSUE THREAD

**Issue by lrjconan** [MelJan/PyDeep#8]
Hi Jan,

Thanks for your nicely written code!
I have a question regarding the unnormalized log probability of visible units of GRBM in [line 906 of model.py in rbm folder](https://github.com/MelJan/PyDeep/blob/b227fe61faabb705dfdae5b73b694d0614fbf4a1/pydeep/rbm/model.py#L906).

It seems that you are not computing it following the Eq. (15 - 20), i.e., the marginal distribution of visible units, in your PLOS one paper.
According to the paper, it should be the log of the sum of two exponential functions.
But it seems not to be the case in the current implementation.
Could you help verify if it is the case? 

Best,

**Comment by lrjconan** [comment]
Sorry that I verified that the code is correct.
I rederived the equation based on your code and found it is equivalent (after some algebraic manipulation) to what you wrote in your paper.
Thanks again for your nice work!

**Comment by MelJan** [comment]
Hi lrjconan,

good that you already figured it out before I had time to answer. 
For a detailed derivation of the distributions also for centered GRBM you can have a look at
https://hss-opus.ub.ruhr-uni-bochum.de/opus4/frontdoor/deliver/index/docId/7713/file/diss.pdf

Best Jan.

**Comment by lrjconan** [comment]
Hi Jan,

Thanks for sharing your thesis!
I have one more question about [the use of beta](https://github.com/MelJan/PyDeep/blob/b227fe61faabb705dfdae5b73b694d0614fbf4a1/pydeep/rbm/model.py#L896) in GaussianRBM.
My understanding is that this beta serves as the coefficient of geometric mean between target and initial (or base) distributions for constructing the intermediate distributions in AIS.
However, IIUC, the geometric mean of two Gaussians does not have mean and variance as the convex combination of their mean and variance respectively, although it is the case for binary units.
Could you help illustrate more about this design of intermediate distributions?

Best,

**Comment by MelJan** [comment]
Hi Irjconan,

that is correct, however, the reason why beta is chosen this way comes from the energy based model perspective. In the binary case this scales the energy down to 0. While in theory you could do this with GRBMs aswell, it gets you into trouble due to sampling from a infinit uniform distribution / Gaussian with infinit variance. That is why you go from a large Gaussian to the final distribution instead, which also makes sense was we know that this distribution is much closer to the final distribtion than the uniform dist. As a rule of thumb, start alwas with the distribution that is closest to the target distribution and simple enough to be able to sample correctly from. 
In theory AIS /PT is guaranteed to sample correctly if the difference between two betas going to zero implies the fisher metric between the two corresponding distributions going to zero. However, a linear schedule of betas does not/does not need to imply a fiher metric schedule. In pratcice it is any infiseable and the schedule of betas is chosen not in a linear fashion.

Best Jan.

**Comment by lrjconan** [comment]
Thanks for the reply!
That makes a lot of sense. My understanding is that the geometric mean is just one general recipe for AIS.
One can have other constructions.
AIS only requires that the successive intermediate distributions do not run into "divide by zero" issue in computing the ratio, which is avoided in your construction.
Thanks again for your nice codebase and well-written paper!
